[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = "0.12.4"
scraper = "0.19.0"
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
url = "2.5.0"
